[package]
name = "universalui_graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1 

[dependencies]
vulkano = "0.33.0"
